development:
  cloud_name: satveerbhantoo
  api_key: '614466756957288'
  api_secret: ic0zmCdAGCtzEXDRpKySZkDx6Sk
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: satveerbhantoo
  api_key: '614466756957288'
  api_secret: ic0zmCdAGCtzEXDRpKySZkDx6Sk
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: satveerbhantoo
  api_key: '614466756957288'
  api_secret: ic0zmCdAGCtzEXDRpKySZkDx6Sk
  enhance_image_tag: true
  static_image_support: false